### ISSUE TITLE
File upload and access

### ISSUE THREAD

**Issue by tabascq** [PuzzleServer/mainpuzzleserver#46]
We need authors to be able to upload puzzle files, and the system to deliver those files to players.

**Comment by morganbr** [comment]
In contrast to the current system, puzzles and other files probably shouldn't be included in the site deployment since that makes it hard for authors to managed. We should consider something like Azure Blob Storage. We also need to consider how to keep players from wandering into puzzles they shouldn't have if it's on blob storage. The easiest approach might be to automatically add some obfuscation in the URL (perhaps picking a random container name for each file). If we want shorter URLs for cases players have to type the URL (e.g. linked files from a puzzle), we could either have authors do manual aka.ms shortening or add a page that redirects to puzzles, but only if the player has access to those puzzles.

**Comment by tabascq** [comment]
Not confident that Azure Blob Storage equates with "easy for authors to manage", but we should certainly consider alternatives so long as it is still straightforward to make a puzzle that has linked content (e.g. a video or some MP3's).

**Comment by morganbr** [comment]
I didn't mean to imply authors would interact with the backing storage. Rather, I was thinking we could have an upload page that accepts a file and takes care of storing it and gives the author a URL back.
