### ISSUE TITLE
Feature Request:  Make pregame puzzles solvable per individual, not per team

### ISSUE THREAD

**Issue by jbodner09** [PuzzleServer/mainpuzzleserver#720]
Ideally, pregame puzzles could be solvable even if you're not on a team, and then the amount you've solved could also be seen by other teams in case they want to add players who are actually serious about the event.  And then, once you're on a team, other teammates' solves of pregame puzzles won't mark the puzzle as solved for you, so you can still have a chance to submit an answer even once you're on a team.  @philipzloh can also explain more.

**Comment by vidapour** [comment]
When flag is on, show submissions per player instead of per team.

**Comment by vidapour** [comment]
@metapzl starting discussion/planning of this item.

**Comment by digit01Wave** [comment]
**How this should work:**
- If we can make it so that each person has their own list
then these could just have no points no problem
- There's a set of puzzles called your team puzzles. Then there's a set of puzzles called your individual puzzles
- For an event you'll have the team puzzles be the event puzzles
- The individual puzzles will be the pre-event puzzles. Those won't score team points. Any account that ever exists can have individual puzzles, they don't need a team to see them or submit

**Comment by jbodner09** [comment]
Closing since an event has successfully done this thanks to the above updates.
